/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RatioRouteImport } from './routes/ratio'
import { Route as ProportionRouteImport } from './routes/proportion'
import { Route as GettingStartedRouteImport } from './routes/getting-started'
import { Route as FinalChallengeRouteImport } from './routes/final-challenge'
import { Route as CoordinatesRouteImport } from './routes/coordinates'
import { Route as IndexRouteImport } from './routes/index'

const RatioRoute = RatioRouteImport.update({
  id: '/ratio',
  path: '/ratio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProportionRoute = ProportionRouteImport.update({
  id: '/proportion',
  path: '/proportion',
  getParentRoute: () => rootRouteImport,
} as any)
const GettingStartedRoute = GettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const FinalChallengeRoute = FinalChallengeRouteImport.update({
  id: '/final-challenge',
  path: '/final-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatesRoute = CoordinatesRouteImport.update({
  id: '/coordinates',
  path: '/coordinates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coordinates': typeof CoordinatesRoute
  '/final-challenge': typeof FinalChallengeRoute
  '/getting-started': typeof GettingStartedRoute
  '/proportion': typeof ProportionRoute
  '/ratio': typeof RatioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coordinates': typeof CoordinatesRoute
  '/final-challenge': typeof FinalChallengeRoute
  '/getting-started': typeof GettingStartedRoute
  '/proportion': typeof ProportionRoute
  '/ratio': typeof RatioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coordinates': typeof CoordinatesRoute
  '/final-challenge': typeof FinalChallengeRoute
  '/getting-started': typeof GettingStartedRoute
  '/proportion': typeof ProportionRoute
  '/ratio': typeof RatioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coordinates'
    | '/final-challenge'
    | '/getting-started'
    | '/proportion'
    | '/ratio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coordinates'
    | '/final-challenge'
    | '/getting-started'
    | '/proportion'
    | '/ratio'
  id:
    | '__root__'
    | '/'
    | '/coordinates'
    | '/final-challenge'
    | '/getting-started'
    | '/proportion'
    | '/ratio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoordinatesRoute: typeof CoordinatesRoute
  FinalChallengeRoute: typeof FinalChallengeRoute
  GettingStartedRoute: typeof GettingStartedRoute
  ProportionRoute: typeof ProportionRoute
  RatioRoute: typeof RatioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ratio': {
      id: '/ratio'
      path: '/ratio'
      fullPath: '/ratio'
      preLoaderRoute: typeof RatioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proportion': {
      id: '/proportion'
      path: '/proportion'
      fullPath: '/proportion'
      preLoaderRoute: typeof ProportionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/final-challenge': {
      id: '/final-challenge'
      path: '/final-challenge'
      fullPath: '/final-challenge'
      preLoaderRoute: typeof FinalChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinates': {
      id: '/coordinates'
      path: '/coordinates'
      fullPath: '/coordinates'
      preLoaderRoute: typeof CoordinatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoordinatesRoute: CoordinatesRoute,
  FinalChallengeRoute: FinalChallengeRoute,
  GettingStartedRoute: GettingStartedRoute,
  ProportionRoute: ProportionRoute,
  RatioRoute: RatioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
