/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GettingStartedRouteImport } from './routes/getting-started'
import { Route as CoordinatesRouteImport } from './routes/coordinates'
import { Route as IndexRouteImport } from './routes/index'

const GettingStartedRoute = GettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinatesRoute = CoordinatesRouteImport.update({
  id: '/coordinates',
  path: '/coordinates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coordinates': typeof CoordinatesRoute
  '/getting-started': typeof GettingStartedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coordinates': typeof CoordinatesRoute
  '/getting-started': typeof GettingStartedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coordinates': typeof CoordinatesRoute
  '/getting-started': typeof GettingStartedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coordinates' | '/getting-started'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coordinates' | '/getting-started'
  id: '__root__' | '/' | '/coordinates' | '/getting-started'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoordinatesRoute: typeof CoordinatesRoute
  GettingStartedRoute: typeof GettingStartedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/getting-started': {
      id: '/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof GettingStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordinates': {
      id: '/coordinates'
      path: '/coordinates'
      fullPath: '/coordinates'
      preLoaderRoute: typeof CoordinatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoordinatesRoute: CoordinatesRoute,
  GettingStartedRoute: GettingStartedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
